name: CI  

on:  
  push:  
    branches: [ main ]  
  workflow_dispatch:  

jobs:  
  build:  
    runs-on: ubuntu-latest  

    steps:  
      - uses: actions/checkout@v3  

      - name: Deploy in EC2  
        env:  
            PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY  }}  
            HOSTNAME: ${{ secrets.HOSTNAME  }}  
            USER_NAME: ${{ secrets.USER_NAME  }}  

        run: |  
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key  
          echo "Attempt to connect to EC2"  
          echo "Connecting as ${USER_NAME}@${HOSTNAME} with private key:"  
          ssh -v -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} << 'ENDSSH'  
            echo "Connected to EC2"  

            DIR="/home/ubuntu/server"  
            if [ ! -d "$DIR" ]; then  
              mkdir server && \
              git clone https://github.com/calm329/domain-search-backend.git server && \
              cd server && \
              npm i  
            else  
              cd server  
              git fetch --all && \
              git reset --hard origin/master && \
              git pull origin master  
              npm i  
            fi  

            npm start  
          ENDSSH
